### ISSUE TITLE
Need to work on backend of api

### ISSUE THREAD

**Issue by Sudhanshu-Ambastha** [Sudhanshu-Ambastha/Poke-3D-Models-Api#3]
**Problem**
Describe the issue or need.

**Solution**
Outline the desired backend functionality.

**Alternatives**
Mention other approaches considered.

**Context**
Add relevant details or examples.

**Comment by rcghpge** [comment]
Problem: need a stable backend and api solution for smooth and robust web functionality.

Solution: 
MongoDB Atlas backend for database. Can implement a FastAPI or Express/NestJS API endpoint to endpoint solution.

Alternatives: API solutions that scale with cost.

Context:
1.) FastAPI - Free, high performance, easy to use, Python-based; requires async programming. Best use case: Prototyping or small-to-medium-sized applications

2.) Express/NestJS - Flexible, MongoDB-friendly, Requires Node.js expertise. Real-time or RESTful APIs.
